export const PIGGY_BANK_PEOPLE = "PIGGY_BANK_PEOPLE";
export const PIGGY_BANK_ADD_PERSON = "PIGGY_BANK_ADD_PERSON";
export const PIGGY_BANK_PAYMENTS = "PIGGY_BANK_PAYMENTS";
export const PIGGY_BANK_EDIT = "PIGGY_BANK_EDIT";